require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EnoncesController do

  # This should return the minimal set of attributes required to create a valid
  # Enonce. As you add validations to Enonce, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnoncesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all enonces as @enonces" do
      enonce = Enonce.create! valid_attributes
      get :index, {}, valid_session
      assigns(:enonces).should eq([enonce])
    end
  end

  describe "GET show" do
    it "assigns the requested enonce as @enonce" do
      enonce = Enonce.create! valid_attributes
      get :show, {:id => enonce.to_param}, valid_session
      assigns(:enonce).should eq(enonce)
    end
  end

  describe "GET new" do
    it "assigns a new enonce as @enonce" do
      get :new, {}, valid_session
      assigns(:enonce).should be_a_new(Enonce)
    end
  end

  describe "GET edit" do
    it "assigns the requested enonce as @enonce" do
      enonce = Enonce.create! valid_attributes
      get :edit, {:id => enonce.to_param}, valid_session
      assigns(:enonce).should eq(enonce)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Enonce" do
        expect {
          post :create, {:enonce => valid_attributes}, valid_session
        }.to change(Enonce, :count).by(1)
      end

      it "assigns a newly created enonce as @enonce" do
        post :create, {:enonce => valid_attributes}, valid_session
        assigns(:enonce).should be_a(Enonce)
        assigns(:enonce).should be_persisted
      end

      it "redirects to the created enonce" do
        post :create, {:enonce => valid_attributes}, valid_session
        response.should redirect_to(Enonce.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved enonce as @enonce" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enonce.any_instance.stub(:save).and_return(false)
        post :create, {:enonce => {  }}, valid_session
        assigns(:enonce).should be_a_new(Enonce)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enonce.any_instance.stub(:save).and_return(false)
        post :create, {:enonce => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested enonce" do
        enonce = Enonce.create! valid_attributes
        # Assuming there are no other enonces in the database, this
        # specifies that the Enonce created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Enonce.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => enonce.to_param, :enonce => { "these" => "params" }}, valid_session
      end

      it "assigns the requested enonce as @enonce" do
        enonce = Enonce.create! valid_attributes
        put :update, {:id => enonce.to_param, :enonce => valid_attributes}, valid_session
        assigns(:enonce).should eq(enonce)
      end

      it "redirects to the enonce" do
        enonce = Enonce.create! valid_attributes
        put :update, {:id => enonce.to_param, :enonce => valid_attributes}, valid_session
        response.should redirect_to(enonce)
      end
    end

    describe "with invalid params" do
      it "assigns the enonce as @enonce" do
        enonce = Enonce.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enonce.any_instance.stub(:save).and_return(false)
        put :update, {:id => enonce.to_param, :enonce => {  }}, valid_session
        assigns(:enonce).should eq(enonce)
      end

      it "re-renders the 'edit' template" do
        enonce = Enonce.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enonce.any_instance.stub(:save).and_return(false)
        put :update, {:id => enonce.to_param, :enonce => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested enonce" do
      enonce = Enonce.create! valid_attributes
      expect {
        delete :destroy, {:id => enonce.to_param}, valid_session
      }.to change(Enonce, :count).by(-1)
    end

    it "redirects to the enonces list" do
      enonce = Enonce.create! valid_attributes
      delete :destroy, {:id => enonce.to_param}, valid_session
      response.should redirect_to(enonces_url)
    end
  end

end
